const dummyData = [
    {
      name: 'Glen Ayienda',
      phone: '+254713322025',
      location: 'Nairobi,juja',
      paymentUniqueId: 'ABC123wr',
      numberOfFamily: 6,
      landInSquareMetres: 100000,
      houseNo: 'c8 kiamuchiri',
      religion: 'islam',
    },
    {
      name: 'Jane Smith',
      phone: '987-654-3210',
      location: 'Los Angeles',
      paymentUniqueId: 'DEF456',
      numberOfFamily: 3,
      landInSquareMetres: 800,
      houseNo: '456 Elm St',
      religion: 'Buddhism',
    },
    {
      name: 'Alice Johnson',
      phone: '555-123-4567',
      location: 'Chicago',
      paymentUniqueId: 'GHI789',
      numberOfFamily: 5,
      landInSquareMetres: 1200,
      houseNo: '789 Oak St',
      religion: 'Islam',
    },{
        name: 'Michael Brown',
        phone: '555-987-6543',
        location: 'San Francisco',
        paymentUniqueId: 'JKL101',
        numberOfFamily: 2,
        landInSquareMetres: 600,
        houseNo: '321 Pine St',
        religion: 'Judaism',
      },
      {
        name: 'Emily Davis',
        phone: '333-222-1111',
        location: 'Miami',
        paymentUniqueId: 'MNO202',
        numberOfFamily: 6,
        landInSquareMetres: 1500,
        houseNo: '567 Beach Rd',
        religion: 'Hinduism',
      },
      {
        name: 'David Wilson',
        phone: '777-888-9999',
        location: 'Dallas',
        paymentUniqueId: 'PQR303',
        numberOfFamily: 4,
        landInSquareMetres: 1100,
        houseNo: '789 Oak St',
        religion: 'Christianity',
      },
      {
        name: 'Sophia Lee',
        phone: '222-333-4444',
        location: 'Seattle',
        paymentUniqueId: 'STU404',
        numberOfFamily: 3,
        landInSquareMetres: 900,
        houseNo: '567 Maple Ave',
        religion: 'Buddhism',
      },
      {
        name: 'Liam Anderson',
        phone: '444-555-6666',
        location: 'Denver',
        paymentUniqueId: 'VWX505',
        numberOfFamily: 5,
        landInSquareMetres: 1300,
        houseNo: '234 Oak St',
        religion: 'Islam',
      },
  ];
  
  export default dummyData;
  